name: geohash
description: A simple geohashing library for dart
version: 0.2.1
author: Adam Stark <llamadonica@gmail.com>
homepage: https://github.com/llamadonica/dart-geohash

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.12
